// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040

package pico

import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)

func TimerInit(sm pio.StateMachine) (pio.StateMachineConfig, uint8, error) {
	offset, err := sm.PIO().AddProgram(timerInstructions, timerOrigin)
	cfg := timerProgramDefaultConfig(offset)
	cfg.SetInShift(false, true, 32)
	sm.Init(offset, cfg)
	return cfg, offset, err
}

// timer

const timerWrapTarget = 1
const timerWrap = 3

var timerInstructions = []uint16{
	0xe022, //  0: set    x, 2
	//     .wrap_target
	0x208a, //  1: wait   1 gpio, 10
	0x4020, //  2: in     x, 32
	0x200a, //  3: wait   0 gpio, 10
	//     .wrap
}

const timerOrigin = -1

func timerProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+timerWrapTarget, offset+timerWrap)
	return cfg
}
